### ISSUE TITLE
Include support to set default shell

### ISSUE THREAD

**Issue by Adophilus** [tom-pollak/lazygit-vscode#5]
## Summary
Currently the shell that's configured is `/bin/bash` but in some OS `/bin/bash` doesn't exist or isn't the default shell. This issue seeks to request for inclusion of support for users to set the default shell that's being used.

### The problem
`/bin/bash` is a presumption on any OS that's linux based, this is largely due to the fact that it might either not exist or is not configured as the default shell and this might result in the error in the attached screenshot:

![image](https://github.com/user-attachments/assets/4ca20d2e-7837-43b6-b364-0c04f86533e8)

**Comment by tom-pollak** [comment]
v0.1.9 it now searches for bash on your path (rather than relying on /bin/bash). On windows it uses cmd.exe. does that solve your problem? I assume almost all computers can access either cmd.exe or bash, and since I rely on some bash functionality (e.g. `which`) I don't know if it's a good idea to allow custom shells.
